services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=mysql+pymysql://ors_db:pTT!CT01@10.2.7.252/testing_db
      - SECRET_KEY=a_very_secret_and_long_random_string_please_change_me_3498ufoij
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  frontend:
    # CORRECTED: The 'build' attribute now has 'context'
    # and 'dockerfile' nested underneath it.
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  default:
    driver: bridge